POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Hayden"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGF5ZGVuIiwiaWF0IjoxNTk0Mjc1NTUxLCJleHAiOjE1OTQyNzkxNTF9.-t6TSqE77N0mLCB7HSzQ37dVZFiQLvHhQupTpHct6ms